package com.fju;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;


public class Demogui extends Tester {

    private JButton okButton;
    public JPanel panelMain;
    private JLabel ajprice;
    private JLabel brprice;
    private JLabel cprice;
    private JLabel appleJuiceLabel;
    private JLabel beerLabel;
    private JLabel colaLabel;
    public JFormattedTextField t1;
    public JFormattedTextField t3;
    public JFormattedTextField t2;
    private JButton payForBankButton;

//    public boolean verify(JComponent component) {
//        JFormattedTextField field1 = (JFormattedTextField) component;
//        return field1.isEditValid();
//    }

    public void setT1() {
        int numt1 = Integer.parseInt(t1.getText());
    }

    public Demogui() {
        super();
        $$$setupUI$$$();
        Frame frame = new JFrame();
        ((JFrame) frame).setContentPane(panelMain);
        ((JFrame) frame).setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setVisible(true);
        // String s1 = new String(String.valueOf(t1));

//        String t1 = Demogui.this.t1.getText();
//        int num1 = Integer.parseInt(t1);


//        ok buttom setting


        okButton.addActionListener(new ActionListener() {
            //            @Override
//            int numt1;
//            Integer t1 = Integer.parseInt(ajprice.getText());
//            public void setT1() {
//                int numt1 = Integer.parseInt(t1.getText());
//            }

            public void actionPerformed(ActionEvent actionEvent) {
                int order = JOptionPane.showConfirmDialog(null, "Here is your order" + "\n" + "Applejuice : " + t1.getText() + "\n" + "Beer : " + t2.getText() + "\n" + "Cola : " + t3.getText() + "\n", "Order", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null);
            }


//    public void message() {
//        String num = JOptionPane.showInputDialog("name");
//        String message = String.format("Welcome, %s, to me", num);
//        System.out.println("message: " + message);
//        JOptionPane.showMessageDialog(null, message);
//
//    }


//    public void Buttunsetting() {
//        JButton okButton = new JButton();
//        JFormattedTextField t1 = new JFormattedTextField();
//        String num = JOptionPane.showInputDialog("num");
//        String message = String.format("Welcome, %s, to me", num);
//        System.out.println("message: " + message);
//        JOptionPane.showMessageDialog(null, message);
//    }

//                                   }

            /**
             * Method generated by IntelliJ IDEA GUI Designer
             * >>> IMPORTANT!! <<<
             * DO NOT edit this method OR call it in your code!
             *
             * @noinspection ALL
             */
        });
        payForBankButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    Desktop.getDesktop().browse(new URI("https://www.cathaybk.com.tw/MyBank"));
                } catch (IOException ioException) {
                    ioException.printStackTrace();
                } catch (URISyntaxException uriSyntaxException) {
                    uriSyntaxException.printStackTrace();
                }

            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridBagLayout());
        brprice = new JLabel();
        brprice.setText("$200");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        panelMain.add(brprice, gbc);
        cprice = new JLabel();
        cprice.setText("$300");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 2;
        panelMain.add(cprice, gbc);
        ajprice = new JLabel();
        ajprice.setHorizontalAlignment(0);
        ajprice.setText("$250");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        panelMain.add(ajprice, gbc);
        colaLabel = new JLabel();
        colaLabel.setHorizontalAlignment(0);
        colaLabel.setText("Cocktail");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        panelMain.add(colaLabel, gbc);
        beerLabel = new JLabel();
        beerLabel.setHorizontalAlignment(0);
        beerLabel.setText("Beer");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        panelMain.add(beerLabel, gbc);
        appleJuiceLabel = new JLabel();
        appleJuiceLabel.setHorizontalAlignment(0);
        appleJuiceLabel.setText("Alcohol");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panelMain.add(appleJuiceLabel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(spacer2, gbc);
        t2 = new JFormattedTextField();
        t2.setColumns(7);
        t2.setHorizontalAlignment(0);
        t2.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        panelMain.add(t2, gbc);
        t3 = new JFormattedTextField();
        t3.setColumns(7);
        t3.setHorizontalAlignment(0);
        t3.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 3;
        panelMain.add(t3, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(spacer3, gbc);
        t1 = new JFormattedTextField();
        t1.setColumns(7);
        t1.setHorizontalAlignment(0);
        t1.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        panelMain.add(t1, gbc);
        okButton = new JButton();
        okButton.setText("check your order");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(okButton, gbc);
        payForBankButton = new JButton();
        payForBankButton.setText("pay for bank");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(payForBankButton, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelMain.add(spacer4, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

}